# Site settings
# in the templates available like {{ site.myvariable }}.
title: YnXu Github Blog.
email: 243071373@qq.com
brand: 闫旭
headline: To every little good thing in life...
description: > # this means to ignore newlines until "baseurl:"
  New Site
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://example.com" # the base hostname & protocol for your site
copyright: 2016 Whatever Company, Inc. All Rights Reserved.

# Build settings
markdown: kramdown

# Account ids
snapwidget: 247552

# Contacts
email: 243071373@qq.com
phone: +86-150-XXXX-9880

# Tracking
googleAnalitycsID: none

